title: DeepCleaners
baseurl: /
permalink: '/:title/'
favicon:
logo_dark: images/Logos/LDC_C.jpg
logo_light: images/Logos/LDC_C.png
hamburger_background_image: /images/Home/SINFIN_ICO.png
bg_image_primary: /images/Home/DEG_01.png
bg_image_primary_opacity: 60
bg_image_secondary: /images/leaf-light-grey.svg
bg_image_product: /images/leaf.svg
snipcart_api_key: ''
footer_text: Copyright 2021 DeepCleaners.
palette: blue
main_menu:
  - title: Inicio
    url: /
    style: link
  - title: Servicios
    url: /services
    style: link
  - title: Contacto
    url: /contact
    style: link
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://enthusiastic-coriander-6b579.netlify.app'
